bitcoin:
  network: testnet
  data-directory: ${BITCOIN_DATA_DIRECTORY:K:/BitcoinJavaNode/testnet-certification}

  p2p:
    port: 18335
    peers: ""
    max-blocks-in-flight-per-peer: 128

  rpc:
    port: 18336
